spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: was
  profiles:
    active: test

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

encrypt:
  key: ${ENCRYPT_KEY}