spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true #data.sql같은 datasource를 시스템 실행 이후에 적용
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.type: trace
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop #create-drop : 테이블 생성 및 종료 시점에 삭제, update : 수정사항만 반영
  datasource:
    url: jdbc:mysql://localhost:3306/skeleton
    username: root
    password: tkfkdg7!

---