spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:configserver:http://${CONFIG_SERVER}
  application:
    name: api
  profiles:
    active: ${CONMOTO_ENV}

encrypt:
  key: ${ENCRYPT_KEY}